version: 1.0.{build}
image: Visual Studio 2019
before_build:
  - nuget restore
build:
  project: GMSAPasswordReader.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: bin\Debug\*.exe
only_commits:
  files:
    - GMSAPasswordReader/
